### ISSUE TITLE
Lack of options for complex resistances/weaknesses cases

### ISSUE THREAD

**Issue by Kiszaner** [LartTyler/MHWDB-Contrib#12]
There are some monsters that have conditions that changes its resistances/weaknesses. Usually these conditions make a resistance a weakness and viceversa, but there are monsters that these conditions just change the value of one resistance/weakness for another value that is not exactly the opposite. See Water Element from the information in-game of a Lavasioth as an example:
![Lavasioth Elements](https://user-images.githubusercontent.com/9079893/60467761-c30ce200-9c57-11e9-91e2-e7f5685ce07f.png)

There are no options to reflect these cases in the Contrib tool, as each element can only appear once on each column when setting both Resistances or Weaknesses.

**Comment by LartTyler** [comment]
Thanks for letting me know. I hadn't realized that monsters could have reduced vulnerability under certain conditions, instead of simply gaining full resistance. I'll get that fixed for you soon.

**Comment by LartTyler** [comment]
This should be resolved with [v1.1.2](https://github.com/LartTyler/MHWDB-Contrib/releases/tag/1.1.2).
