### ISSUE TITLE
Cannot add new armor

### ISSUE THREAD

**Issue by mingjunlu** [LartTyler/MHWDB-Contrib#17]
**Description**
A new armor couldn't be added after submitting the form.
Got "Internal Server Error" message instead.

**To Reproduce**
1. Go to "Objects > Armor"
2. Click on "+ Add New" button
3. Fill out the form
4. Click on "Save" button

**Expected behavior**
A new armor should be added to the armor list.

**Screenshots**
<img width="779" alt="add-new-armor-interal-server-error" src="https://user-images.githubusercontent.com/40516784/64551186-117ce200-d367-11e9-83da-f8c761450bdb.png">

**Environment**
 - OS: macOS Mojave 10.14.6
 - Browser: Safari 12.1.2 & Vivaldi 2.7.1628.33

**Comment by LartTyler** [comment]
This is likely an issue with the API and not with the editor. I'm going to open a ticket over in that repository and reference this one.

**Comment by LartTyler** [comment]
This is resolved with [LartTyler/MHWDB-API 1.15.1](https://github.com/LartTyler/MHWDB-API/releases/tag/1.15.1). Thanks for bringing this to my attention!
