### ISSUE TITLE
Blank screen when skill rank added

### ISSUE THREAD

**Issue by mingjunlu** [LartTyler/MHWDB-Contrib#18]
**Description**
The entire screen goes blank when a new rank is added to a skill.

**To Reproduce**
1. Go to "Objects > Skills"
2. Click on "+ Add New" button or "Edit" button
3. Click on "+ Add Rank" button
4. Fill in the description
5. Click on "Save" button

**Expected behavior**
A new rank should be added to the skill.

**Screenshots**
<img width="823" alt="螢幕快照 2019-09-10 上午1 14 01" src="https://user-images.githubusercontent.com/40516784/64551957-cf54a000-d368-11e9-8495-f881e944800a.png">

**Environment**
 - OS: macOS Mojave 10.14.6
 - Browser: Safari 12.1.2 & Vivaldi 2.7.1628.33

**Comment by LartTyler** [comment]
This should be resolved with [1.2.1](https://github.com/LartTyler/MHWDB-Contrib/releases/tag/1.2.1). Thanks for letting me know about the issue!

**Comment by mingjunlu** [comment]
@LartTyler The screen also goes blank when I try to add a rank to an armor set bonus. Should I open a new issue?

**Comment by LartTyler** [comment]
A new ticket would be great, thanks!

**Comment by mingjunlu** [comment]
No problem! 💁‍♂️ [Here's the link](https://github.com/LartTyler/MHWDB-Contrib/issues/26)
