### ISSUE TITLE
Cannot filter items with modal opened

### ISSUE THREAD

**Issue by mingjunlu** [LartTyler/MHWDB-Contrib#25]
**Description**
Letters cannot be typed to filter/search items while a modal is opened.

**To Reproduce**
1. Go to "Objects > Armor"
2. Click on "Add New" button
3. Click on "Add Skill", "Add Item", or "Add Slot" button
4. Click on "Make a selection..." button
5. Try to type

**Expected behavior**
Letters should show up and the items should be filtered correspondingly when the user types.

**Screenshots**
<img width="742" alt="螢幕快照 2019-09-10 上午11 23 43" src="https://user-images.githubusercontent.com/40516784/64583178-a19c4500-d3c2-11e9-818d-31aa4d1ed1e1.png">

**Environment**
 - OS: macOS Mojave 10.14.6
 - Browser: Safari 12.1.2 & Vivaldi 2.7.1628.33

**Additional context**
This issue also happens when trying to select and add a skill to a decoration. However, things work fine when a modal is not opened (e.g., when picking an armor's type, rank, or armor set).

**Comment by LartTyler** [comment]
This should be resolved with [v1.2.2](https://github.com/LartTyler/MHWDB-Contrib/releases/tag/1.2.2). I'm pretty sure that I found every instance of this happening, but please let me know if I missed any.
