### ISSUE TITLE
Safari shows "Invalid Date" in Events page

### ISSUE THREAD

**Issue by mingjunlu** [LartTyler/MHWDB-Contrib#31]
**Description**
The date format in Events page cannot be parsed correctly by Safari. Expected to show date strings but got "Invalid Date" instead.

**Screenshots**
![safari-invalid-date](https://user-images.githubusercontent.com/40516784/65478886-f4dfbe80-debd-11e9-8e72-dc8d2784c24d.png)

**Environment**
 - OS: macOS Mojave 10.14.6
 - Browser: Safari 13.0 (14608.1.49)

**Notes**
It's probably Safari's own weird behavior (couldn't recognize the date format `2019-07-05T00:00:00+0000` from the API). Chrome, Firefox, and Vivaldi work totally fine otherwise.

**Comment by LartTyler** [comment]
Because _of course_ it doesn't work in Safari... :sob: Thanks for letting me know, I'll get it fixed with the next release.

**Comment by mingjunlu** [comment]
Some say that Safari is the new IE... 🤦‍♂️

**Comment by LartTyler** [comment]
This should be resolved with [v1.3.0](https://github.com/LartTyler/MHWDB-Contrib/releases/tag/1.3.0).
