### ISSUE TITLE
Item's rarity cannot be set over 8

### ISSUE THREAD

**Issue by mingjunlu** [LartTyler/MHWDB-Contrib#33]
**Description**
When adding/editing an item, the rarity  cannot be set over 8. Any value greater than 8 would be automatically replaced with 8. I guess there is some kind of max-limit? Since literally like everything in _Iceborne_ has a rarity greater than 8, it would be nice if that max-limit setting could be removed (if any).

**To Reproduce**
1. Go to "Objects > Items"
2. Click on "Add New" or "Edit" button
3. Type something greater than 8 (e.g., two-digit numbers or 9) in the "Rarity" field

**Expected behavior**
Any value greater than 8 should be entered without being replaced with the number 8.

**Screenshots**
<img width="1267" alt="螢幕快照 2019-10-03 上午11 23 58" src="https://user-images.githubusercontent.com/40516784/66097290-598ecd80-e5d0-11e9-8c81-921aa2a24d66.png">

**Environment**
 - OS: macOS Mojave 10.14.6
 - Browser: Safari 13.0.1 & Vivaldi 2.8.1664.43

**Comment by LartTyler** [comment]
This should be resolved with [v1.3.1](https://github.com/LartTyler/MHWDB-Contrib/releases/tag/1.3.1). You may need to clear your cache to see the changes.
