### ISSUE TITLE
Level 4 decoration slots needed

### ISSUE THREAD

**Issue by mingjunlu** [LartTyler/MHWDB-Contrib#34]
**Description**
When adding/editing the slots of an armor, there are only 3 options available. Since _Iceborne_ introduces level 4 decoration slots (see the screenshot in Notes), it would be great if the same option could be provided.

**Preferred solution**
The level 4 decoration slot option should be provided when adding or editing an armor.

**Screenshots**
<img width="551" alt="螢幕快照 2019-10-03 下午12 01 45" src="https://user-images.githubusercontent.com/40516784/66098812-bdb49000-e5d6-11e9-9cb5-ad38ef0be031.png">

**Notes**
![Monster Hunter World_ Iceborne_20191003120056](https://user-images.githubusercontent.com/40516784/66098801-b1c8ce00-e5d6-11e9-9387-e05cbe7c3fc4.jpg)

**Comment by LartTyler** [comment]
This should be resolved with [v1.3.1](https://github.com/LartTyler/MHWDB-Contrib/releases/tag/1.3.1). You may need to clear your cache to see the changes.
