### ISSUE TITLE
Blank screen when adding skills to armor

### ISSUE THREAD

**Issue by mingjunlu** [LartTyler/MHWDB-Contrib#38]
**Description**
While adding or editing an armor, the entire screen will go blank if "Add Skill" button is clicked before the data are fetched.

**To Reproduce**
1. Go to "Objects > Armor"
2. Click on "Add New" button
3. Click on "Add Skill" while the spinner icon is spinning

**Screenshots**
<img width="996" alt="螢幕快照 2019-10-27 下午3 54 16" src="https://user-images.githubusercontent.com/40516784/67631533-cc8b1b80-f8d2-11e9-985f-ac2b47263917.png">

**Environment**
 - OS: macOS Mojave 10.14.6
 - Browser: Safari 13.0.2 & Vivaldi 2.8.1664.44

**Notes**
I think this one may be related to issue #26.

**Comment by LartTyler** [comment]
I believe this was resolved, but never closed. If this is still an issue, feel free to reopen the ticket!
