### ISSUE TITLE
Decorations with Level 4 Slot

### ISSUE THREAD

**Issue by Kradus** [LartTyler/MHWDB-Contrib#39]
**Description**
When i want to create a Level 4 Decorations then i can not save it. I can selected the Level 4 but when i want to save it always this message occurred under the level selection: "This value should be 3 or less."

**Preferred solution**
I can save the decorations.

**Comment by LartTyler** [comment]
This should be resolved with [API v1.16.2](https://github.com/LartTyler/MHWDB-API/releases/tag/1.16.2)
