### ISSUE TITLE
Editing from Charms

### ISSUE THREAD

**Issue by Kradus** [LartTyler/MHWDB-Contrib#40]
**Description**
I can not save new Ranks from Charms or create Charms. Everytime i want to create a new Charm rank i get the following error: "Could not update: You must provide a value for the following field(s): [ranks[3].name]"

**Preferred solution**
I can add new charm ranks to old charms and can create new charm ranks.

**Screenshots:**
![grafik](https://user-images.githubusercontent.com/7405404/69129530-d60d3b00-0aae-11ea-9edc-fcb0f53faa9b.png)

**Comment by LartTyler** [comment]
Thanks for the heads up. I'm able to recreate the issue on my end, and should be able to resolve it quickly.

**Comment by LartTyler** [comment]
This should be resolved with [Contrib v1.3.2](https://github.com/LartTyler/MHWDB-Contrib/releases/tag/1.3.2). You may need to clear your browser's cache in order to see the changes.
