### ISSUE TITLE
Add charm ranks

### ISSUE THREAD

**Issue by Kradus** [LartTyler/MHWDB-Contrib#49]
**Description**
I can not save new Ranks from Charms or create Charms. Everytime i want to create a new Charm rank i get the following error: "Request failed with status code 500"

**Preferred solution**
The exception which is thrown on server site should be fixed.

![grafik](https://user-images.githubusercontent.com/7405404/74010084-ee417780-4984-11ea-9b9c-065a09b3d144.png)

**Comment by LartTyler** [comment]
I am looking into this now.

**Comment by LartTyler** [comment]
@Kradus This should be resolved with [v1.18.1](https://github.com/LartTyler/MHWDB-API/releases/tag/1.18.1).
